name: Update documentation

on:
  push:
    paths:
    - 'path_to_schema'

jobs:
  triggerUpdate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Trigger documentation Update
      run: |
        curl -XPOST -u "bufferbot:${GH_ACTIONS_WORKFLOW_TRIGGER_TOKEN}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${DOCUMENTATION_REPOSITORY}/dispatches \
          --data '{"event_type": "${CURRENT_REPOSITORY}"}'
      env:
        GH_ACTIONS_WORKFLOW_TRIGGER_TOKEN: ${{ secrets.GH_ACTIONS_WORKFLOW_TRIGGER_TOKEN }}
        DOCUMENTATION_REPOSITORY: ${{ secrets.DOCUMENTATION_REPOSITORY }}
        CURRENT_REPOSITORY: ${{ github.event.repository.name }}